### ISSUE TITLE
File size

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/Keen-UI#115]
I realized that KeenUI is taking up a whopping ~450kb making it 10 times more than Vue itself. Without asking for a deadline of anything, would it be possible to compress the total size?

Maybe there's a recommended way of importing the components that's better than importing them in any component where I need it? Is it better (and possible) to import only once in the root VM?

**Comment by JosephusPaye** [comment]
Are you minifying your output JS and CSS? 

The minified version of Keen UI is (212.2 KB - 159 KB for JS and 62.2 KB for CSS).

**Comment by EmilMoe** [comment]
I'm bundling it, so it's hard to see how much the size is exactly. My total size is now 1,4 mb, but might as well be my own misitake of the way i import things. Do you consider it better to use KeenUI global rather than many imports? Maybe the compiled files has includede the same things many times this way?

**Comment by JosephusPaye** [comment]
Yeah, if you are using more than half of the components, I would suggest importing Keen UI in your root Vue component and registering it to use globally.

The size could especially increase if you use files from `lib/` like so:

```js
import UiButton from 'keen-ui/lib/UiButton';
```

This is because the files in `lib/` are standalone (contain all their own dependencies) and a lot them contain the same dependencies. 

For example, `UiAlert` in `lib/` also includes a copy of `UiButton`, which includes `UiMenu`, `UiPopover`, `UiIcon` and `UiTooltip`, etc.

**Comment by EmilMoe** [comment]
Ah thanks.. I will have to do some rewriting about this, this is probably my problem then since I have many imports from the lib.
