### ISSUE TITLE
ui-select should return only value, without text

### ISSUE THREAD

**Issue by murbanowicz** [JosephusPaye/Keen-UI#125]
Hi,

I think it's an issue that ui-select puts text and value in value, instead of value.
Only value is needed for logic behind and this is common practice.
Could you correct that?

**Comment by zephyrpersonal** [comment]
Can't agree any more.
Providing a prop to set output format of value would be nice.

**Comment by JosephusPaye** [comment]
We don't write only the option's `.value` property to the `value` prop when a selection is made because we use the object (through the `value` prop) to highlight the currently selected value.

You can fix this using a computed property (Keen UI v1.0):

```vue
<ui-select :options="colours" v-model="mySelect">Favourite colour</ui-select>
```

```js
{
    data: function() {
        return {
            colours: [{ label: 'Red', value: 'red' }, { label: 'Blue', value: 'blue' }, { label: 'Green', value: 'green' }],
            mySelect: ''
        };
    },

    computed: {
        mySelectValue: function() {
            return this.mySelect.value || this.mySelect;
        }
    }
}
```

`mySelectValue` will now always have the `value` of the selected option.
