### ISSUE TITLE
Tabs bug if it places in modal

### ISSUE THREAD

**Issue by lavezzi1** [JosephusPaye/Keen-UI#176]
Hello,

If I place tabs in modal window I get this bug. It just doesn't computed. Fullwidth active line. 
![screen shot 2016-11-15 at 10 06 08](https://cloud.githubusercontent.com/assets/10686894/20290479/2deaa836-ab1b-11e6-9ac0-926da9cd398d.png)

How to fix that?

**Comment by JosephusPaye** [comment]
@lavezzi1,

The reason this happens is that the modal is hidden (`display: none`) when the tabs are initially rendered, making the active tab indicator to have a width of zero.

In v1.0, this can be fixed by listening for the modal `open` event and calling `refreshIndicator()` on the UiTabs component.
