### ISSUE TITLE
How to use those components?

### ISSUE THREAD

**Issue by roslaneshellanoo** [JosephusPaye/Keen-UI#177]
There is no instructions with examples, i see only "view source" links to github.
Im using the ES6 import method globally. Then just trying to add some component in in the template(App.vue).
I'm getting a bunch errors.
Please provide some simple demo how to use those wonderful components

**Comment by roslaneshellanoo** [comment]
vue.js?3de6:2643[Vue warn]: Property or method "$els" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in component <ui-button>)

**Comment by JosephusPaye** [comment]
Are you trying to use it with Vue 2? Keen UI doesn't support Vue 2 yet. If you're using Vue 1, see the Readme for usage instructions.

**Comment by Shuunen** [comment]
It's not really clear on the readme.

When I read "Requirements : Vue.js (^v1.0.21)" I understood Vue v1.0.21 & superior, so Vue v2.

Something like "Requirements : Vue.js 1 (^v1.0.21) not v2 yet" would be really clearer :)

**Comment by citycide** [comment]
@Shuunen you may want to look into semver and how its symbols tell you version ranges. You would be correct if the requirements stated "Vue.js >1.0.21", however the `^` symbol means something like "within the current major version" which in this case is `1.0.0`.

Since minor versions of semver-compatible libraries shouldn't contain breaking changes, the `^` symbol here means Keen UI should work until Vue makes breaking changes at which point all bets are off.

I'm not saying it couldn't be _explicitly_ stated, but the semver range used in the readme is correct in saying Keen UI isn't expected to work with Vue 2 yet.

**Comment by Shuunen** [comment]
I was not aware of this, even if it's correct, I don't see the problem with being explicit :face_with_head_bandage:

**Comment by greatramu** [comment]
@JosephusPaye hii. Thank you for such a beautiful library, i really like KeenUI and want to use in my Vue2 based project. Would love to hear from you about vue 2 support. Also, a very simple example to work with ES6 and components would be great.

**Comment by JosephusPaye** [comment]
v1.0 with Vue 2 support is ready and will be released tomorrow.

**Comment by JosephusPaye** [comment]
[Keen UI v1.0.0](https://josephuspaye.github.io/Keen-UI/1.0.0/) with support for Vue 2 has now been [released](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.0.0).
