### ISSUE TITLE
UiDatepicker opens too fast on mobile

### ISSUE THREAD

**Issue by dohomi** [JosephusPaye/Keen-UI#194]
Hello,
I just tried the `UiDatepicker` component and it opens too fast, its very difficult to scroll down a form where the picker is present because the widget opens instantly. Maybe a slight `debounce` would be nice here

**Comment by JosephusPaye** [comment]
HI @dohomi,

This seems to be a problem with [Drop](https://github.com/HubSpot/drop/), which uses the [`touchstart` event](https://github.com/HubSpot/drop/blob/master/src/js/drop.js#L29-L32) on touch devices, instead of, or in addition to, the `click` event. This is why the datepicker dropdown is a little too sensitive and may interfere with scrolling.

Will see how this can be solved for the next release.

**Comment by JosephusPaye** [comment]
The dropdown positioning plugin has been switched from Drop/Tether to Tippy.js/Popper.

This should fix the issue.

Closing for now, reopen if this is still an issue.
