### ISSUE TITLE
feedback on UiSelect on mobile iOS not fitting into view

### ISSUE THREAD

**Issue by dohomi** [JosephusPaye/Keen-UI#197]
Hello,
the `UiSelect` component is on the demo page not fitting into the screen on mobile. This results into some unusual scrolling behavior with the need scrolling the outer div container down to see the end of the component. I think it would be great if the `UiSelect` would expand in the middle of the component and respects the outer window size that the whole component is visible. The `AngularMaterial` library has a nice approach to tackle this: https://material.angularjs.org/latest/demo/select

**Comment by JosephusPaye** [comment]
Hi,

I considered the approach Angular Material used and decided against it, since it adds further complexity to UiSelect (already the biggest single component) and it is not always possible to keep the whole select dropdown visible in the viewport.

I'll probably go with using UiPopover (it automatically positions itself to stay in the viewport) for the UiSelect dropdown if I were to do this. It's the same approach taken with UiDatepicker and UiMenu.

Thanks for the suggestion, though.
