### ISSUE TITLE
UiButtons with dropdown menu stick to top of page

### ISSUE THREAD

**Issue by mcmillenb** [JosephusPaye/Keen-UI#243]
If I have a UiButton with an open dropdown menu and I then try to scroll past it down the page, the dropdown menu sticks to the top of the page. If this is expected behavior, it would be nice to have an option to disable it.

Browser: Chrome 56 on Mac OS X 10

**Comment by JosephusPaye** [comment]
@mcmillenb,

This is expected behavior, when the dropdown is open, it will position itself to stay visible in the viewport, even when scrolling.

Why open the dropdown and then scroll without interacting with it or closing it? Would like to know your use case as this (IMO) is not common.

If it is, I wouldn't mind adding an option to disable the auto positioning, however this will disable auto positioning at the edges of the viewport (for example, when the button is almost at the bottom of the viewport and there isn't enough space below the button for the dropdown, so it drops up).

**Comment by mcmillenb** [comment]
@JosephusPaye you're right, it's probably not a common use case. I think sometimes I might have a dropdown or popover which just has a message pertaining to the element it's visually adjacent to. The user doesn't need to interact with it so they might scroll away but still see that message, now removed from its context.

**Comment by vuesify** [comment]
在某个容器上使用 `position: absolute` 定位后，不能在其内部正常使用 `UiPopover` 组件，下面是一个简单的演示示例：[http://jsfiddle.net/vuesify/qx5y6znz/3/embedded/#Result](http://jsfiddle.net/vuesify/qx5y6znz/3/embedded/#Result)

**Comment by JosephusPaye** [comment]
Closing for now. Reopen if there's still an issue.

Translation from Google Translate

@nkcjs,

<details>
<summary>Translation from Google Translate</summary>
After positioning with position: absolute on a container, the UiPopover component cannot be used inside it. Here is a simple demonstration example.
</details>
<br>
That should be fixed with the switch to Popper.js, the new positioning engine.
