### ISSUE TITLE
button do not work in IE?

### ISSUE THREAD

**Issue by xiaolongyuan** [JosephusPaye/Keen-UI#25]
![image](https://cloud.githubusercontent.com/assets/3142363/15170115/76ecb1da-1775-11e6-802e-4f8fd9b9caa7.png)

**Comment by JosephusPaye** [comment]
Hi, the reason it's not centering is due to a flexbox bug in IE.

This was fixed in https://github.com/JosephusPaye/Keen-UI/commit/1e453f739d813a0c35d26dbc077fb62b9a5f8aec and will be part of the next release.

**Comment by xiaolongyuan** [comment]
thanks

**Comment by JosephusPaye** [comment]
This fix has landed in [v0.8.8](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.8).

**Comment by nivv** [comment]
@JosephusPaye Sorry for necromancing this issue. But the bug fix introduces another problem if the UiButton is shrunk because of the containing div.

What happens:
<img width="161" alt="skarmklipp 2016-06-28 20 17 44" src="https://cloud.githubusercontent.com/assets/4033930/16427402/75f9f076-3d6d-11e6-8d04-c45b01520e30.png">

Desired:
<img width="125" alt="skarmklipp 2016-06-28 20 17 59" src="https://cloud.githubusercontent.com/assets/4033930/16427412/81449f1c-3d6d-11e6-8c35-5b4fc82effc0.png">
