### ISSUE TITLE
UiSnackbar break line not working

### ISSUE THREAD

**Issue by rorc** [JosephusPaye/Keen-UI#250]
I have to use `nl2br($message)` and `:allow-html="true"` for breaking lines.

**Comment by JosephusPaye** [comment]
Hi @rorc,

HTML doesn't support `\n` for line breaks (except in textarea), that's why you need `<br>`, and `nl2br()` converts new lines to `<br>`.

Also, by default, the message for UiSnackbar does not support HTML, but the `allowHtml` prop allows for using HTML in the message. This is working as intended.
