### ISSUE TITLE
The Tabs component `setActiveTab()` method should really be a prop?

### ISSUE THREAD

**Issue by gbmhunter** [JosephusPaye/Keen-UI#264]
As it stands, the active tab can be set by the user by calling the `setActiveTab()` method of the `Tabs` component.

Keeping in line with the vue data-driven model, should the active tab be driven with a string/numeral `prop` instead?

A method makes things a little ugly, I had to use `Vue.nextTick()` to be able to switch to a newly created tab using the current `setActiveTab()` as it was not present in the DOM yet.

**Comment by JosephusPaye** [comment]
The reason this isn't just a prop is because there is more that goes into rendering the active tab correctly:
 
- the tab's id
- the tab's index in the list of tabs
- the tab's root element in the DOM

The best way to change all three of these is by putting it behind a method, which is [`setActiveTab`](https://github.com/JosephusPaye/Keen-UI/blob/master/src/UiTabs.vue#L299).

**Comment by gbmhunter** [comment]
Hi @JosephusPaye , thanks for the reply.

Could those three things you mentioned above not be hidden behind a prop? E.g. internally, you watch the prop and when it changes, perform those actions.
