### ISSUE TITLE
Confirm in a Modal - Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by llops** [JosephusPaye/Keen-UI#279]
Hi!

Calling a Confirm inside a Modal throws an error:
![keen-error](https://cloud.githubusercontent.com/assets/1206248/23995809/607d1204-0a4b-11e7-9aef-e9a08a51b503.png)

Demo: http://codepen.io/llops/pen/ryGExo

**Comment by JosephusPaye** [comment]
Currently multiple open modals (UiConfirm uses a modal) are not supported due to the way we implement focus containment. This is something that I'm working on fixing for the next release.

**Comment by orckid-lab** [comment]
Hi, this issue has not been fixed yet. Can you please explain what the restrict focus is for?

On my project, if I import the components I need manually, and overwrite/comment the logic inside restrictFocus, my implementation of multiple modals work.

Otherwise, I am unable to click within the "inputs" that renders within the last/second modal.

However the solution described above breaks all the styling, as it inherits the styling from the components on compilation.

**Comment by orckid-lab** [comment]
The way this is implemented causes a recursion and leads to the error above I believe. But I am unable to understand what does this function serves for (both in ui modal and keen ui compiled version)

**Comment by JosephusPaye** [comment]
Hi @orckid-lab,

Restrict focus is used to keep focus in the modal when tabbing around.

If the keyboard focus leaves the modal, the user could be interacting with hidden elements behind the modal, which shouldn't happen.

This has been fixed in Keen UI next, which is being tested and will be released soon.

To try it, you can install using:

```
npm install JosephusPaye/Keen-UI#next
```

**Comment by JosephusPaye** [comment]
Fix released in [v1.1.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.1.0).
