### ISSUE TITLE
Uncaught SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by chertpong** [JosephusPaye/Keen-UI#311]
When I use Keen-UI and open in old browser, it doesn't seem to compile ES6 in util.js to ES5

**Comment by JosephusPaye** [comment]
Hello @chertpong,
 
This happens when the ES6 files from Keen UI are not compiled to ES5. This could be a problem with your Babel configuration, perhaps excluding any files from `node_modules`. This is the default setup if you're using the `vue-cli` templates.

See this issue for a fix: https://github.com/JosephusPaye/Keen-UI/issues/295.
