### ISSUE TITLE
Toolbar, hide nav icon does not work

### ISSUE THREAD

**Issue by Jdruwe** [JosephusPaye/Keen-UI#32]
It seems that hide-nav-icon="true" does not work on the toolbar. Also why are prop names in de docs in camelCase but differently in the real code, example: nav-icon (code) vs navIcon (docs)?

**Comment by JosephusPaye** [comment]
Because HTML attributes are case insensitive, props that are camel cased in Javascript (e.g. `hideNavIcon`) have to be kebab cased (e.g. `hide-nav-icon`) when written in the HTML template. The prop names in the docs are the Javascript versions. See the docs for [Vue component props](https://vuejs.org/guide/components.html#camelCase-vs-kebab-case) for more information. 

As for why it isn't working, I think it's because you haven't used the [dynamic syntax](https://vuejs.org/guide/components.html#Literal-vs-Dynamic) to pass down the boolean:

Try this and it should work (notice the colon **:** before the prop name):

```html
<ui-toolbar title="My App" :hide-nav-icon="true"></ui-toolbar>
```

Or the short form:

```html
<ui-toolbar title="My App" hide-nav-icon></ui-toolbar>
```
