### ISSUE TITLE
Value posted by multiple ui-select

### ISSUE THREAD

**Issue by mm-x** [JosephusPaye/Keen-UI#340]
I encountered the following scenario:

I have a form where I require a multiple select. Implemented according per documentation.
`[
	{
		"label": "Option 1",
		"value": 1
	},
	{
		"label": "Option 2",
		"value": 2
	},
	{
		"label": "Option 3",
		"value": 3
	}
]`

when I am posting, I am sending the form object rather than the models, for my form contains a huge amount of fields an I don't want to have to write v-model on all of them.

Thus using the following: `axios.post(this.route, new FormData($event.target))`

My issue is that when posting to server, I expect the value received to be an array of values [1, 2], but instead I receive values concatenated by commas within an array i.e [ "1,2" ] if I were to select for instance Option 1 and Option 2.

Current workaround: 
`<input v-for="option in form.options" type="hidden" name="options[]" :value="option.value"/>`

Can you please advise if this is something that can be altered to behave like a native multiple select?

**Comment by JosephusPaye** [comment]
Hi @mm-x,

This one is tricky. I initially tried the workaround you're using but it decided against it, since, as the number of options grow, there'll be lot of hidden input elements (not free). Also the `name="options[]"` convention is a PHP-specific idiom that may not be used by other languages or frameworks.

With the comma separation, you can split the string into an array of values when you receive them on the server. For this, remove the `[]` after the `name` attribute, and handle

Example using PHP ([`explode`](http://php.net/manual/en/function.explode.php)):

```php
$options = explode(",", $field); // $field is from the GET/POST data
```

**Comment by mm-x** [comment]
Thanks for the suggestion however in my scenario, my solution was more appropriate as if I used the above, I would not benefit from the native validation of the php framework in use (Laravel), and would have to sort of filter the request before the validation run (thus extra development), not even mention that I had more than one fields impacted by this on multiple forms, meaning I would have to handle this multiple times around. But I understand and agree to your point which in fact would not be ideal for other server-side language.
