### ISSUE TITLE
Is there a way to clear the UIDatepicker?

### ISSUE THREAD

**Issue by nelsonpecora** [JosephusPaye/Keen-UI#374]
First off, this library is great. We've implemented a lot of these components in our web app, and I just got a [note from one of our devs](https://github.com/clay/clay-kiln/issues/993) that there's no way to clear the UIDatepicker.

From the little bit of research I did, it doesn't seem like the Material Design spec actually says how those should be cleared, and other component libraries are [exploring](https://github.com/callemall/material-ui/issues/2204) [different](https://github.com/angular/material/issues/8159) options. I'm thinking it might make sense to allow users to click the selected date to clear it? (perhaps this isn't enabled by default, but rather through a prop). What do you think?

**Comment by JosephusPaye** [comment]
Hey @nelsonpecora,

This is something I've thought of, and I'm leaning more towards a "X" button like the one we have on UiAutocomplete:

![image](https://user-images.githubusercontent.com/5924865/32859893-fab00e26-caa3-11e7-9fd3-206c3e875ecd.png)

Maybe if not in the input, then right next to it, at the right.

I think clicking the selected date to clear it might be confusing to users as it's not obvious, and they might be expecting the the dropdown to open for selecting a different date when they click it.

I'll play around with different options and see how it turns out. At the very least, we should have a method for clearing/resetting the selected date - which would allow for a button external to the component to be used for clearing it.

**Comment by nelsonpecora** [comment]
I think you're right, an external button / icon to clear the date makes more sense than an implicit affordance in the picker itself.

**Comment by JosephusPaye** [comment]
Added a new method `clear` to clear the selected date. https://github.com/JosephusPaye/Keen-UI/commit/01d96aab8ba2e7d9bea6ed2120a0ea58759026cb

This can be called when an external clear button is clicked.

**Comment by JosephusPaye** [comment]
Released in [v1.1.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.1.0).
