### ISSUE TITLE
Is there a sample guide i can implement my grid and typography?

### ISSUE THREAD

**Issue by midascodebreaker** [JosephusPaye/Keen-UI#58]
I have successfully integrated all components but there is no grid...
and typography...

if i wanna include for example grid of bootsrap 4 , or materializecss grid or bulma...

How can i do it? any ideas?

thanks... Hope someone can help me , add this in my test app

**Comment by breadlesscode** [comment]
You can use [Gutenberg](http://matejlatin.github.io/Gutenberg/) for Typographie and [Flexbox Grid](http://flexboxgrid.com/) as Gridsystem if you like.

**Comment by midascodebreaker** [comment]
how can i implement it with this package keen ui?
can you give me your sample code to easily hook it up?
thanks

**Comment by alnour-altegani** [comment]
@midascodebreaker 
- simply add flexbox grid css link to your html file
- add class to your keen ui element or wrap keen ui element with div has class from flexbox-grid

**Comment by EmilMoe** [comment]
Use any grid system you like, these are only UI elements. CSS Flexbox is amazing.

I think this is answered already, @JosephusPaye ?

**Comment by JosephusPaye** [comment]
Yes, closing for now.

**Comment by nucamoz** [comment]
Why are you advising to use any grid by adding a css link to a html file? Then why Keen-UI EXIST in the first place?))

**Comment by derekphilipau** [comment]
@JosephusPaye, I have spent the past three days testing a number of Vue UI component frameworks and have come to the conclusion that your Keen UI components are the best.  Really well-crafted, thank you!  However, I think you could add information about "Recommended Gridsystems" to a Readme or docs.  Because there are so many grids to choose from, and it's not clear if some grids work better or are more "compatible" with your components.  For now I will try Flexbox Grid as others have suggested, thank you.

**Comment by JosephusPaye** [comment]
Hi @derekphilipau,

Thanks for the suggestion. I'll keep that in mind when updating the docs next.

**Comment by derekphilipau** [comment]
@JosephusPaye, Flexbox Grid was _too_ basic for me, now I'm using [MDL](https://github.com/google/material-design-lite) and your components are working great with it, thanks.
