### ISSUE TITLE
Custom Icons

### ISSUE THREAD

**Issue by victor-ponamariov** [JosephusPaye/Keen-UI#66]
Hi there!

Is it possible to use custom icons, not from google material collections? I realize there is no easy way for doing that. Then what would you recommend, because sometimes it's really a necessity to use custom icon in menu dropdown for example, or a button. Completely hack CSS by overwriting `ui-icon material-icons ui-autocomplete-icon search` styles, for example? Or maybe there is more elegant way?

Thanks for your amazing package!

**Comment by JosephusPaye** [comment]
Hey @victor-ponamariov,

If you have direct access to the icon template (e.g. if it's not in another component, you can set the class and icon to use a different icon set). 

Example using Font Awesome ([see here for demo](http://codepen.io/JosephusPaye/pen/VjKbqp)):

```html
<ui-icon class="fa" icon="fa-camera-retro" remove-text></ui-icon>
``` 

The icon class is set to `fa`, which is the class for Font Awesome and the `remove-text` prop is added to remove the inner text used by the Material Icons.

If you don't have direct access to the `<ui-icon>` template, for example, in a menu, there's no way to override the default `material-icons`, for now. You could override the CSS, but you'll have to use JS to remove the inner text used for the ligatures. 

This might be fixed in a future release, but it's not the priority for now.

**Comment by victor-ponamariov** [comment]
Okay, thank you!

**Comment by JosephusPaye** [comment]
In v1.0, most components that accept an icon now have an `icon` slot, which can be used for custom icons.
