### ISSUE TITLE
UiRadioGroup

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/Keen-UI#73]
First it would be nice to have a boolean for radio groups for `required`, so I make sure the user choose one or the other.

Second. I'm having some issue with how it's displayed when I load it. I tried to create a JSFiddle but realized I couldn't find a link to Keen UI anywhere. Not sure if it's supported in JSFiddle at all?

You can see my source at the JSFiddle, but the result I get on my page is http://cloudho.st/i/vvP58JEF.png

For some reason the circles are large and the vertical option doesn't to apply.

https://jsfiddle.net/on0fk68x/1/

**Comment by JosephusPaye** [comment]
As of v0.8.8, Keen UI doesn't support validation for the Boolean inputs components (UiCheckbox, UiRadio and UiSwitch). As a workaround, you can set a default (which will force the user to accept it (do nothing) or change it to their choice).

Keen UI doesn't work in JSFiddle because of [dominus](https://github.com/bevacqua/dominus), which uses [poser](https://github.com/bevacqua/poser/blob/6651ca8a1e767cbd42e640fe14363cfb0d0d7f2e/src/browser.js#L5-L12) which tries to create an `iframe` and append it to the body before the document has loaded.

I use CodePen for online demos and you can use this link for a template with Vue and Keen UI already included: [http://codepen.io/pen?template=NrKmPQ](http://codepen.io/pen?template=NrKmPQ)

For direct links to Keen UI, you can use NPM CDN:

```
https://npmcdn.com/keen-ui@0.8.8/dist/min/keen-ui.min.css
https://npmcdn.com/keen-ui@0.8.8/dist/keen-ui.js
```

Also, I think the reason the circles appear wrong is because you haven't reset the CSS box-sizing:

```css
* {
    box-sizing: border-box;
}
```

**Comment by EmilMoe** [comment]
Thanks. That solved the dot error.

Do you have an idea why they are not vertical?
And do you plan to support validation for boolean inputs? Although I think it only makes sense for a RadioGroup

**Comment by JosephusPaye** [comment]
You have a slight typo in the template: `vertial` instead of `vertical`.

No immediate plans though I think it would be a good addition.

**Comment by EmilMoe** [comment]
Damn, thanks. Facepalm. Hard to work with not enough sleep.

**Comment by JosephusPaye** [comment]
Closing for now. Might revisit in the future.
